name: wasli
description: "A new Flutter project."

publish_to: "none"

# ANDROID VERSION
version: 1.0.0+1
# IOS VERSION
# version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common Packages
  flutter_lints: ^6.0.0
  equatable: ^2.0.5
  collection: ^1.18.0
  json_annotation: ^4.8.1
  share_plus: ^11.0.0
  url_launcher: ^6.2.6
  fluttertoast: ^8.2.5
  lottie: ^3.1.0
  dartz: ^0.10.1
  uuid: ^4.4.0
  infinite_scroll_pagination: ^5.1.0
  pinput: ^5.0.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  liquid_pull_to_refresh: ^3.0.1
  carousel_slider: ^5.1.1
  flutter_html: any
  flutter_gen: any # Auto Generate assets files [icons,images,fonts ,etc..]
  cached_network_image: ^3.4.1
  responsive_framework: ^1.5.1
  device_preview: ^1.3.1
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.0.17
  dotted_border: ^3.1.0
  video_player: ^2.9.1
  gap: ^3.0.1

  # Service Locator
  get_it: ^8.0.3
  injectable: ^2.3.2

  # StateManagement
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0

  # Local Storages
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4

  # Path Utils
  path_provider: ^2.1.5

  # Network Clients
  dio: ^5.4.0
  pretty_dio_logger: ^1.4.0

  # Media && Files
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  pdfx: ^2.8.0
  mime: ^2.0.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.0
  bounce: ^1.0.2
  liquid_pull_refresh: ^1.0.6
  iconsax_flutter: ^1.0.1
  permission_handler: ^12.0.0+1
  location: ^8.0.1
  geocoding: ^4.0.0
  skeletonizer: ^2.0.1
  country_pickers: ^3.0.1
  flutter_animate: ^4.5.2
  animate_do: ^4.2.0
  google_maps_flutter: ^2.14.0
  smooth_page_indicator: ^1.2.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: any
  flutter_launcher_icons: ^0.14.3
  flutter_gen_runner: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - packages/timezone/data/latest_all.tzf
    - assets/launcher_icon/
    - assets/icons/
    - assets/images/
    - assets/native_splash/
    - assets/animations/
    - assets/popular_sites_icons/
    - assets/fonts/almaraia/
    - assets/illustrations/

  fonts:
    - family: Almaraia
      fonts:
        - asset: assets/fonts/almaraia/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/almaraia/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/almaraia/Almarai-Regular.ttf
          weight: 500
        - asset: assets/fonts/almaraia/Almarai-Bold.ttf
          weight: 600
        - asset: assets/fonts/almaraia/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/almaraia/Almarai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/almaraia/Almarai-ExtraBold.ttf
          weight: 900

flutter_gen:
  output: lib/core/config/values/
  fonts:
    enabled: false

  integrations:
    image: false
    flutter_svg: false
